### ISSUE TITLE
Request - Translation to Spanish

### ISSUE THREAD

**Issue by kSHOU98** [Piggy3590/LC_NotEnoughSubtitle#1]
I find your mod for LC that adds subtitles to the ship incredibly good. I would like to be able to translate it into Spanish to complement it with my mod pack. Could you upload a new version with parts of the dialogues already translated by me to your Thunderstore page?

[DepositItemsDeskPatch.txt](https://github.com/Piggy3590/LC_NotEnoughSubtitle/files/13653931/DepositItemsDeskPatch.txt)
[NotEnoughSubtitleES.txt](https://github.com/Piggy3590/LC_NotEnoughSubtitle/files/13653932/NotEnoughSubtitleES.txt)

Thank you,
from ChomusukeDEV to Piggy3590.

**Comment by Piggy3590** [comment]
https://thunderstore.io/c/lethal-company/p/Piggy/NotEnoughSubtitleSPA/
The icon may appear as KR because it has changed since uploading

**Comment by kSHOU98** [comment]
Okay, great! Thank you for taking the time for my request. I have no issue with the icon, so no worries. Just knowing that people will now understand what the ship's speaker says makes me happy (even though they already had a rough idea). Seriously, thank you so much; you're incredibly kind.

I'm looking forward to getting home from my job to test it ♥️.
